---

- name: install supervisor using apt
  apt: name=supervisor state=latest update_cache=true cache_valid_time=3600

- name: add program to supervise
  template: src=etc/supervisor/conf.d/myconf.conf dest=/etc/supervisor/conf.d/{{ item.name }}.conf
  with_items: programs_to_supervise
  when: programs_to_supervise|length > 0

- name: Put all the programs in the right state
  supervisorctl: name={{ item.name }} state={{ item.state|default('started') }}
  with_items: programs_to_supervise
  when: programs_to_supervise|length > 0
